### ISSUE TITLE
Support new, faster lz4 compression in 3.15 kernel

### ISSUE THREAD

**Issue by binarybana** [mystilleef/FedoraZram#10]
By writing to /sys/block/zram$i/comp_algorithm, ZRAM can be made to use the faster lz4 compression algorithm (if available). 

Right now I've just put a line:
``echo lz4 > /sys/block/zram$i/comp_algorithm``

in the first line of the last for loop in zramstart, but since this is compilation dependent, then I'm not sure how this change could/should best be made. But I figured I would document my changes here for anyone interested.

**Comment by Hubbitus** [comment]
My kernels compiled for Fedora with lz4 support. So it will be cool see it used. Thanks.
